#!/usr/bin/env sh
set -eu
SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$SCRIPT_DIR/sonder-runtime.sh"
if [ -z "${SONDER_PYTHON:-}" ]; then
  echo "[sonder] ERROR: no bundled or system Python runtime was found." >&2
  exit 3
fi

export SONDER_NUM_THREAD=${SONDER_NUM_THREAD:-$(getconf _NPROCESSORS_ONLN 2>/dev/null || echo 4)}
export SONDER_NUM_GPU=${SONDER_NUM_GPU:-999}
export SONDER_NUM_BATCH=${SONDER_NUM_BATCH:-512}
export OLLAMA_FLASH_ATTENTION=${OLLAMA_FLASH_ATTENTION:-1}
export SONDER_ENDLESS_TOTAL=${SONDER_ENDLESS_TOTAL:-30}
export SONDER_ENDLESS_LANGUAGES=${SONDER_ENDLESS_LANGUAGES:-python,javascript,powershell,cpp,csharp}
export SONDER_ENDLESS_TIER=${SONDER_ENDLESS_TIER:-fast}
export SONDER_ENDLESS_WORKERS=${SONDER_ENDLESS_WORKERS:-4}
export SONDER_ENDLESS_TIMEOUT=${SONDER_ENDLESS_TIMEOUT:-10}
export SONDER_ENDLESS_REPAIRS=${SONDER_ENDLESS_REPAIRS:-2}
export SONDER_ENDLESS_SLEEP=${SONDER_ENDLESS_SLEEP:-2}
export SONDER_ENDLESS_STOP_AFTER_NO_PROGRESS=${SONDER_ENDLESS_STOP_AFTER_NO_PROGRESS:-1}

exec "$SONDER_PYTHON" "$SCRIPT_DIR/endless_train.py" "$@"
