"""Exception-code tables: NTSTATUS, FAST_FAIL subcodes, POSIX signals."""
from __future__ import annotations


NTSTATUS = {
    0x80000002: "EXCEPTION_DATATYPE_MISALIGNMENT",
    0x80000003: "EXCEPTION_BREAKPOINT",
    0x80000004: "EXCEPTION_SINGLE_STEP",
    0xC0000005: "EXCEPTION_ACCESS_VIOLATION",
    0xC0000006: "EXCEPTION_IN_PAGE_ERROR",
    0xC0000008: "STATUS_INVALID_HANDLE",
    0xC0000017: "STATUS_NO_MEMORY",
    0xC000001D: "EXCEPTION_ILLEGAL_INSTRUCTION",
    0xC0000025: "EXCEPTION_NONCONTINUABLE_EXCEPTION",
    0xC0000026: "EXCEPTION_INVALID_DISPOSITION",
    0xC000008C: "EXCEPTION_ARRAY_BOUNDS_EXCEEDED",
    0xC000008D: "EXCEPTION_FLT_DENORMAL_OPERAND",
    0xC000008E: "EXCEPTION_FLT_DIVIDE_BY_ZERO",
    0xC000008F: "EXCEPTION_FLT_INEXACT_RESULT",
    0xC0000090: "EXCEPTION_FLT_INVALID_OPERATION",
    0xC0000091: "EXCEPTION_FLT_OVERFLOW",
    0xC0000092: "EXCEPTION_FLT_STACK_CHECK",
    0xC0000093: "EXCEPTION_FLT_UNDERFLOW",
    0xC0000094: "EXCEPTION_INT_DIVIDE_BY_ZERO",
    0xC0000095: "EXCEPTION_INT_OVERFLOW",
    0xC0000096: "EXCEPTION_PRIV_INSTRUCTION",
    0xC00000FD: "EXCEPTION_STACK_OVERFLOW",
    0xC0000135: "STATUS_DLL_NOT_FOUND",
    0xC0000142: "STATUS_DLL_INIT_FAILED",
    0xC000013A: "STATUS_CONTROL_C_EXIT",
    0xC0000194: "EXCEPTION_POSSIBLE_DEADLOCK",
    0xC0000374: "STATUS_HEAP_CORRUPTION",
    0xC0000409: "STATUS_STACK_BUFFER_OVERRUN",
    0xC0000417: "STATUS_INVALID_CRUNTIME_PARAMETER",
    0xC0000420: "STATUS_ASSERTION_FAILURE",
    0xC0000602: "STATUS_FAIL_FAST_EXCEPTION",
    0x40000015: "STATUS_FATAL_APP_EXIT",
    0x4000001F: "STATUS_WX86_BREAKPOINT",
    0xE06D7363: "CPP_EH_EXCEPTION",
    0xE0434352: "CLR_EXCEPTION",
    0x887A0005: "DXGI_ERROR_DEVICE_REMOVED",
    0x887A0006: "DXGI_ERROR_DEVICE_HUNG",
    0x887A0007: "DXGI_ERROR_DEVICE_RESET",
    0x887A0020: "DXGI_ERROR_DRIVER_INTERNAL_ERROR",
}

GPU_DEVICE_LOST_CODES = frozenset({0x887A0005, 0x887A0006, 0x887A0007, 0x887A0020})

# ExceptionInformation[0] of STATUS_STACK_BUFFER_OVERRUN (__fastfail code).
FAST_FAIL = {
    0: "FAST_FAIL_LEGACY_GS_VIOLATION",
    1: "FAST_FAIL_VTGUARD_CHECK_FAILURE",
    2: "FAST_FAIL_STACK_COOKIE_CHECK_FAILURE",
    3: "FAST_FAIL_CORRUPT_LIST_ENTRY",
    4: "FAST_FAIL_INCORRECT_STACK",
    5: "FAST_FAIL_INVALID_ARG",
    6: "FAST_FAIL_GS_COOKIE_INIT",
    7: "FAST_FAIL_FATAL_APP_EXIT",
    8: "FAST_FAIL_RANGE_CHECK_FAILURE",
    9: "FAST_FAIL_UNSAFE_REGISTRY_ACCESS",
    10: "FAST_FAIL_GUARD_ICALL_CHECK_FAILURE",
    11: "FAST_FAIL_GUARD_WRITE_CHECK_FAILURE",
    12: "FAST_FAIL_INVALID_FIBER_SWITCH",
    13: "FAST_FAIL_INVALID_SET_OF_CONTEXT",
    14: "FAST_FAIL_INVALID_REFERENCE_COUNT",
    18: "FAST_FAIL_INVALID_JUMP_BUFFER",
    19: "FAST_FAIL_MRDATA_MODIFIED",
    20: "FAST_FAIL_CERTIFICATION_FAILURE",
    21: "FAST_FAIL_INVALID_EXCEPTION_CHAIN",
    22: "FAST_FAIL_CRYPTO_LIBRARY",
    23: "FAST_FAIL_INVALID_CALL_IN_DLL_CALLOUT",
    24: "FAST_FAIL_INVALID_IMAGE_BASE",
    25: "FAST_FAIL_DLOAD_PROTECTION_FAILURE",
    26: "FAST_FAIL_UNSAFE_EXTENSION_CALL",
    27: "FAST_FAIL_DEPRECATED_SERVICE_INVOKED",
    28: "FAST_FAIL_INVALID_BUFFER_ACCESS",
    29: "FAST_FAIL_INVALID_BALANCED_TREE",
    30: "FAST_FAIL_INVALID_NEXT_THREAD",
    31: "FAST_FAIL_GUARD_ICALL_CHECK_SUPPRESSED",
    32: "FAST_FAIL_APCS_DISABLED",
    33: "FAST_FAIL_INVALID_IDLE_STATE",
    34: "FAST_FAIL_MRDATA_PROTECTION_FAILURE",
    35: "FAST_FAIL_UNEXPECTED_HEAP_EXCEPTION",
    36: "FAST_FAIL_INVALID_LOCK_STATE",
    37: "FAST_FAIL_GUARD_JUMPTABLE",
    38: "FAST_FAIL_INVALID_LONGJUMP_TARGET",
    39: "FAST_FAIL_INVALID_DISPATCH_CONTEXT",
    40: "FAST_FAIL_INVALID_THREAD",
    41: "FAST_FAIL_INVALID_SYSCALL_NUMBER",
    42: "FAST_FAIL_INVALID_FILE_OPERATION",
    43: "FAST_FAIL_LPAC_ACCESS_DENIED",
    44: "FAST_FAIL_GUARD_SS_FAILURE",
    46: "FAST_FAIL_GUARD_EXPORT_SUPPRESSION_FAILURE",
    47: "FAST_FAIL_INVALID_CONTROL_STACK",
    48: "FAST_FAIL_SET_CONTEXT_DENIED",
    50: "FAST_FAIL_HEAP_METADATA_CORRUPTION",
}

# AV ExceptionInformation[0].
ACCESS_KINDS = {0: "read", 1: "write", 8: "execute"}

SIGNALS = {
    1: "SIGHUP", 2: "SIGINT", 3: "SIGQUIT", 4: "SIGILL", 5: "SIGTRAP", 6: "SIGABRT",
    7: "SIGBUS", 8: "SIGFPE", 9: "SIGKILL", 10: "SIGUSR1", 11: "SIGSEGV", 12: "SIGUSR2",
    13: "SIGPIPE", 14: "SIGALRM", 15: "SIGTERM", 16: "SIGSTKFLT", 17: "SIGCHLD",
    24: "SIGXCPU", 25: "SIGXFSZ", 31: "SIGSYS",
}

_GENERIC_SI_CODES = {0: "SI_USER", 0x80: "SI_KERNEL", -1: "SI_QUEUE", -6: "SI_TKILL"}
SI_CODES = {
    "SIGSEGV": {1: "SEGV_MAPERR", 2: "SEGV_ACCERR", 3: "SEGV_BNDERR", 4: "SEGV_PKUERR",
                8: "SEGV_MTESERR", 9: "SEGV_CPERR"},
    "SIGBUS": {1: "BUS_ADRALN", 2: "BUS_ADRERR", 3: "BUS_OBJERR", 4: "BUS_MCEERR_AR",
               5: "BUS_MCEERR_AO"},
    "SIGILL": {1: "ILL_ILLOPC", 2: "ILL_ILLOPN", 3: "ILL_ILLADR", 4: "ILL_ILLTRP",
               5: "ILL_PRVOPC", 6: "ILL_PRVREG", 7: "ILL_COPROC", 8: "ILL_BADSTK"},
    "SIGFPE": {1: "FPE_INTDIV", 2: "FPE_INTOVF", 3: "FPE_FLTDIV", 4: "FPE_FLTOVF",
               5: "FPE_FLTUND", 6: "FPE_FLTRES", 7: "FPE_FLTINV", 8: "FPE_FLTSUB"},
    "SIGTRAP": {1: "TRAP_BRKPT", 2: "TRAP_TRACE"},
}
# Signals whose si_addr is the faulting address.
FAULT_ADDRESS_SIGNALS = frozenset({"SIGSEGV", "SIGBUS", "SIGILL", "SIGFPE"})


def ntstatus_name(code: int) -> str:
    return NTSTATUS.get(int(code) & 0xFFFFFFFF, "0x%08X" % (int(code) & 0xFFFFFFFF))


def fast_fail_name(subcode: int) -> str:
    return FAST_FAIL.get(int(subcode), "FAST_FAIL_%d" % int(subcode))


def signal_name(number: int) -> str:
    return SIGNALS.get(int(number), "SIG%d" % int(number))


def si_code_name(signal: str, code: int) -> str:
    table = SI_CODES.get(signal, {})
    code = int(code)
    if code in table:
        return table[code]
    return _GENERIC_SI_CODES.get(code, str(code))


__all__ = [
    "ACCESS_KINDS", "FAST_FAIL", "FAULT_ADDRESS_SIGNALS", "GPU_DEVICE_LOST_CODES", "NTSTATUS",
    "SIGNALS", "SI_CODES", "fast_fail_name", "ntstatus_name", "si_code_name", "signal_name",
]
