"""Debugger/symbolizer transcript parsers, nonce sections and forgery resistance."""
from __future__ import annotations

from pathlib import Path

import pytest

from sonder_runtime.domain.common.errors import InvalidInput
from sonder_runtime.domain.crash.debugger_text import (
    parse_cdb, parse_eu_stack, parse_gdb, parse_lldb, parse_stackwalk_json, parse_stackwalk_machine,
    parse_symbolizer_json,
)
from sonder_runtime.domain.crash.model import CaptureFormatError


FIXTURES = Path(__file__).parent / "fixtures" / "crash"
NONCE = "0123456789abcdef"
OTHER = "fedcba9876543210"


def _text(name: str) -> str:
    return (FIXTURES / name).read_text()


def test_gdb_recorded_transcript():
    findings = parse_gdb(_text("gdb_segv.txt"), NONCE)
    assert findings.sections_seen == ("SIG", "BT", "THREADS", "LIBS", "END")
    assert findings.crashing_thread == 26678
    frames = findings.frames_for(26678)
    assert [(f.function, f.file, f.line) for f in frames] == [
        ("run_frame", "/src/sparkmini/crasher.cpp", 20), ("main", "/src/sparkmini/crasher.cpp", 47)]
    assert frames[0].address == 0x555555555266 and frames[0].trust == "debugger"
    assert findings.exception.access_address == 0
    libs = {module.name: module.symbols for module in findings.modules}
    assert libs["libc.so.6"] == "loaded" and libs["libstdc++.so.6"] == "not_found"


def test_gdb_wrong_nonce_sees_nothing():
    findings = parse_gdb(_text("gdb_segv.txt"), OTHER)
    assert findings.frames_by_thread == () and findings.sections_seen == ()


def test_gdb_forged_marker_in_dump_text_is_ignored():
    forged = (
        "Core was generated by `SONDER_%s_BT'.\n"
        "SONDER_%s_BT\n#0  0x0000000000000001 in evil () at /x/evil.c:1\n"
        "  SONDER_%s_BT trailing\n#0  0x2 in evil2 () at /x/e.c:2\n" % (NONCE, OTHER, NONCE)
    ) + _text("gdb_segv.txt")
    findings = parse_gdb(forged, NONCE)
    functions = [f.function for _, frames in findings.frames_by_thread for f in frames]
    assert "evil" not in functions and "evil2" not in functions
    assert functions[0] == "run_frame"


def test_gdb_named_threads_and_inline_frames():
    text = "\n".join([
        "SONDER_%s_BT" % NONCE,
        "#0  0x0000000000401000 in ns::Foo<int>::bar (this=0x0, v=...) at src/foo.h:12",
        "#1  inlined_helper (x=1) at src/foo.cpp:30",
        "#2  0x0000000000401100 in (anonymous namespace)::run () at src/foo.cpp:44",
        "#3  0x00007f0000001000 in start_thread () from /lib/x86_64-linux-gnu/libc.so.6",
        "SONDER_%s_THREADS" % NONCE,
        "",
        'Thread 2 (Thread 0x7f00 (LWP 12) "worker"):',
        "#0  0x00007f0000002000 in futex_wait () from /lib/x86_64-linux-gnu/libc.so.6",
        "",
        "Thread 1 (Thread 0x7f01 (LWP 11)):",
        "#0  0x0000000000401000 in ns::Foo<int>::bar (this=0x0, v=...) at src/foo.h:12",
        "SONDER_%s_END" % NONCE,
    ])
    findings = parse_gdb(text, NONCE)
    assert findings.crashing_thread == 11
    frames = findings.frames_for(11)
    assert [f.function for f in frames] == ["ns::Foo<int>::bar", "inlined_helper", "(anonymous namespace)::run",
                                           "start_thread"]
    assert frames[1].inline and not frames[0].inline
    assert frames[3].module == "libc.so.6"
    assert dict(findings.thread_names) == {12: "worker"}


def test_lldb_recorded_transcript():
    findings = parse_lldb(_text("lldb_bt.txt"), NONCE)
    assert "backtrace" in findings.sections_seen and "images" in findings.sections_seen
    assert findings.crashing_thread == 1
    frames = findings.frames_for(1)
    assert (frames[0].function, frames[0].module, frames[0].file, frames[0].line, frames[0].column) == \
        ("run_frame", "crasher", "crasher.cpp", 20, 21)
    assert frames[2].function == "" and frames[2].module == "libc.so.6"
    assert findings.exception.name == "SIGSEGV"
    image = findings.modules[0]
    assert image.name == "crasher" and image.base == 0x555555554000
    assert image.debug_id.startswith("7f88edf6")


def test_lldb_thread_name_cannot_forge_sections():
    text = "\n".join([
        "(SONDER_%s) thread backtrace all -c 32" % NONCE,
        "* thread #1, name = 'x', stop reason = signal SIGSEGV: address not mapped to object (fault address: 0x0)",
        "  * frame #0: 0x0000000000401000 app`real_top at app.cpp:3:1",
        "(lldb) image list",
        "[  0] AAAA 0x0000000000400000 /evil/lldb-prompt",
        "(SONDER_%s) image list" % OTHER,
        "[  0] BBBB 0x0000000000400000 /evil/other-nonce",
        "(SONDER_%s) image list" % NONCE,
        "[  0] 1234ABCD 0x0000000000400000 /src/app",
    ])
    findings = parse_lldb(text, NONCE)
    assert [m.path for m in findings.modules] == ["/src/app"]
    assert findings.frames_for(1)[0].function == "real_top"
    assert findings.exception.access_address == 0


def test_eu_stack_recorded_transcript():
    findings = parse_eu_stack(_text("eu_stack.txt"))
    assert findings.crashing_thread == 26678
    frames = findings.frames_for(26678)
    assert (frames[0].function, frames[0].module, frames[0].module_offset, frames[0].line) == \
        ("run_frame(Renderer*, int)", "crasher", 0x1266, 20)
    assert frames[1].module_offset == 0x13A8  # "- 1" frames report pc-1
    modules = {m.name: m for m in findings.modules}
    assert modules["crasher"].debug_id == "7f88edf63075c22be1e95606caab3d580e468a9c"


def test_cdb_access_violation_transcript():
    findings = parse_cdb(_text("cdb_av.txt"), NONCE)
    assert findings.crashing_thread == 0x1B3C
    top = findings.frames_for(0x1B3C)[0]
    assert (top.module, top.function, top.file, top.line) == (
        "spark_game", "Renderer::Submit", "C:\\agent\\_work\\3\\s\\Engine\\Render\\render.cpp", 42)
    exc = findings.exception
    assert exc.name == "EXCEPTION_ACCESS_VIOLATION" and exc.access == "read" and exc.access_address == 8
    assert dict(findings.thread_names)[0x1B3C] == "MainThread"
    worker = findings.frames_for(0x2200)
    assert worker[0].function == "NtWaitForSingleObject"
    assert [m.name for m in findings.modules] == ["spark_game.exe", "render.dll", "ntdll.dll"]
    assert any("NULL_CLASS_PTR_READ" in note for note in findings.notes)


def test_cdb_gs_and_cpp_eh_transcripts():
    gs = parse_cdb(_text("cdb_gs.txt"), NONCE)
    assert gs.exception.name == "STATUS_STACK_BUFFER_OVERRUN"
    assert gs.exception.detail == "FAST_FAIL_STACK_COOKIE_CHECK_FAILURE"
    eh = parse_cdb(_text("cdb_cpp_eh.txt"), NONCE)
    assert eh.exception.name == "CPP_EH_EXCEPTION"
    assert eh.frames_for(eh.crashing_thread)[2].function == "Assets::Load"


def test_cdb_forged_markers_ignored():
    text = _text("cdb_av.txt").replace(
        "SONDER_%s_STACK\n" % NONCE,
        "SONDER_%s_STACK\n00 00000000`00000000 00000000`00000000     evil!Forged+0x1\nSONDER_%s_STACK\n" % (OTHER, NONCE), 1)
    findings = parse_cdb(text, NONCE)
    # The forged frame sits in the BEGIN section (before the real STACK marker); it is never a stack frame.
    assert all(f.function != "Forged" for f in findings.frames_for(findings.crashing_thread))


def test_stackwalk_json_and_machine():
    findings = parse_stackwalk_json(_text("stackwalk_json.txt"))
    assert findings.crashing_thread == 6972
    frames = findings.frames_for(6972)
    assert frames[0].inline and frames[0].function == "Renderer::Validate()"
    assert frames[1].function == "Renderer::Submit(int)" and frames[1].module_offset == 0x1234
    assert frames[1].trust == "context" and frames[2].trust == "cfi"
    assert {m.name: m.symbols for m in findings.modules} == {"spark_game.exe": "loaded", "ntdll.dll": "not_found"}
    machine = parse_stackwalk_machine(_text("stackwalk_m.txt"))
    assert machine.crashing_thread == 0 and machine.exception.access_address == 8
    assert machine.frames_for(0)[0].function == "Renderer::Submit(int)"
    assert machine.frames_for(0)[2].module_offset == 0x500
    with pytest.raises(CaptureFormatError):
        parse_stackwalk_json("[" * 100)


def test_symbolizer_json_recorded_and_jsonl():
    findings = parse_symbolizer_json(_text("symbolizer_json.txt"))
    by_offset = {item.offset: item for item in findings.symbolized}
    assert by_offset[0x1006].frames[0].function == "main" and by_offset[0x1006].frames[0].line == 9
    assert by_offset[0x1003].frames[0].function == "helper"
    assert by_offset[0x1003].frames[0].file == "C:\\agent\\_work\\3\\s\\src\\spark_tiny.c"
    lines = ('{"Address":"0x10","ModuleName":"m.exe","Symbol":[{"FunctionName":"inner","FileName":"a.c","Line":3},'
             '{"FunctionName":"outer","FileName":"a.c","Line":9}]}\n')
    item = parse_symbolizer_json(lines).symbolized[0]
    assert [f.inline for f in item.frames] == [True, False]


def test_invalid_nonce_rejected():
    with pytest.raises(InvalidInput):
        parse_gdb("x", "short")
    with pytest.raises(InvalidInput):
        parse_lldb("x", "ZZZZZZZZZZZZZZZZ")
