"""Deterministic project files for the arena-shooter generation harness."""

from __future__ import annotations

from pathlib import Path


PROJECT_FILE_NAME = "FpsGame_Skeleton.csproj"
PROJECT_FILE = """\
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <!-- Verify/ loads this exact assembly name as a plain file reference. -->
    <AssemblyName>FpsGameSonder</AssemblyName>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Raylib-cs" Version="8.0.0" />
  </ItemGroup>
</Project>
"""


def ensure_project_file(project: str | Path) -> Path:
    """Create the stable C# project manifest without overwriting a run.

    Skeleton source is intentionally regenerated by ``--reset``. The project
    manifest is not model output, though: it is harness-owned plumbing needed
    before the first baseline build can be meaningful. Keeping it separate
    prevents a reset or interrupted run from deleting it.
    """
    root = Path(project)
    root.mkdir(parents=True, exist_ok=True)
    path = root / PROJECT_FILE_NAME
    if not path.exists():
        path.write_text(PROJECT_FILE, encoding="utf-8", newline="\n")
    return path
