"""Deterministic session fixtures shared by the export parity and ATIF tests.

Only APIs that already existed before the ATIF export was added are used, so
``session_export_parity_golden.json`` can be (re)generated by running
:func:`golden` against the pre-change code (``PYTHONPATH=<main checkout>``)
and compared byte-for-byte against the current default export.
"""
from __future__ import annotations

import json
from pathlib import Path

PARENT = "s-parity"
CHILD = "child-session-c1"
SECRET = "sk-parityFIXTURE0123456789abcdef"
PASSWORD = "hunter2-parity-pw"


def _ts(second: int) -> str:
    return "2026-09-01T12:00:%02d.000000Z" % second


def build_session_repo(path):
    """A durable session store with a parent (tools, provider usage, subagent)
    and one delegated child session."""
    from sonder_runtime.adapters.persistence.session_repository import SQLiteSessionRepository

    repo = SQLiteSessionRepository(Path(path), max_read_limit=1000)
    events = [
        ("session.started", {"status": "active"}),
        ("model.requested", {"request_id": "r1", "turn_id": "t1", "tier": "code",
                              "prompt": "list files", "system": "You are Sonder.",
                              "history": [], "options": {}, "tools": []}),
        ("user.message", {"content": "list files, my api_key=%s" % SECRET, "turn_id": "t1",
                          "request_id": "r1"}),
        ("provider.requested", {"turn_id": "t1", "request_id": "r1", "attempt_id": "a1",
                                "provider": "ollama", "operation": "chat",
                                "payload": {"model": "qwen3:8b"}}),
        ("provider.responded", {"turn_id": "t1", "request_id": "r1", "attempt_id": "a1",
                                "response": {"model": "qwen3:8b", "prompt_eval_count": 120,
                                             "eval_count": 30}}),
        ("tool.call", {"content": json.dumps({"path": ".", "password": PASSWORD},
                                              sort_keys=True, separators=(",", ":")),
                       "turn_id": "t1", "call_id": "call-1", "name": "directory_tree"}),
        ("tool.result", {"content": "[\"a.py\",\"b.py\"]", "result": ["a.py", "b.py"],
                         "turn_id": "t1", "call_id": "call-1", "name": "directory_tree"}),
        ("tool.call", {"content": "{\"cmd\":\"cat secrets\"}", "turn_id": "t1",
                       "call_id": "call-2", "name": "run_code"}),
        ("tool.failed", {"call_id": "call-2", "error_code": "FORBIDDEN"}),
        ("model.response", {"content": "Found a.py and b.py. token=%s" % SECRET,
                            "turn_id": "t1", "request_id": "r1"}),
        ("subagent.spawned", {"subagent_id": "c1", "role": "reviewer"}),
        ("subagent.completed", {"subagent_id": "c1", "result_ref": "res-1"}),
        ("model.requested", {"request_id": "r2", "turn_id": "t2", "tier": "code",
                              "prompt": "again", "system": "You are Sonder.",
                              "history": [], "options": {}, "tools": []}),
        ("user.message", {"content": "private note", "turn_id": "t2", "request_id": "r2"}),
        ("provider.requested", {"turn_id": "t2", "request_id": "r2", "attempt_id": "a2",
                                "provider": "ollama", "operation": "chat",
                                "payload": {"model": "qwen3:8b"}}),
        ("provider.failed", {"turn_id": "t2", "request_id": "r2", "attempt_id": "a2",
                             "error_code": "DEPENDENCY_UNAVAILABLE"}),
        ("model.failed", {"turn_id": "t2", "request_id": "r2",
                          "error_code": "DEPENDENCY_UNAVAILABLE"}),
        ("error.raised", {"error_code": "DEPENDENCY_UNAVAILABLE"}),
    ]
    for index, (kind, payload) in enumerate(events, start=1):
        repo.append(PARENT, kind, payload, event_id="ev-p-%02d" % index,
                    occurred_at_utc=_ts(index))
    # Retention marker on the failed tool observation (sequence 9).  It is
    # deliberately not a transcript-role event: on the pre-change code a
    # marker on user.message/model.response/tool.call/tool.result makes
    # ``SessionQueryEngine._transcript`` raise KeyError('content').
    repo.append(PARENT, "session.retention.applied",
                {"targets": [{"sequence": 9, "privacy_class": "private"}]},
                event_id="ev-p-99", occurred_at_utc=_ts(40))
    child = [
        ("model.requested", {"request_id": "cr1", "turn_id": "cr1", "tier": "code",
                              "prompt": "review", "system": "", "history": [],
                              "options": {}, "tools": []}),
        ("user.message", {"content": "review a.py", "turn_id": "cr1", "request_id": "cr1"}),
        ("provider.requested", {"turn_id": "cr1", "request_id": "cr1", "attempt_id": "ca1",
                                "provider": "ollama", "operation": "chat",
                                "payload": {"model": "qwen3:4b"}}),
        ("provider.responded", {"turn_id": "cr1", "request_id": "cr1", "attempt_id": "ca1",
                                "response": {"model": "qwen3:4b",
                                             "usage": {"prompt_tokens": 50,
                                                       "completion_tokens": 9}}}),
        ("model.response", {"content": "a.py looks fine", "turn_id": "cr1",
                            "request_id": "cr1"}),
    ]
    for index, (kind, payload) in enumerate(child, start=1):
        repo.append(CHILD, kind, payload, event_id="ev-c-%02d" % index,
                    occurred_at_utc=_ts(20 + index))
    return repo


def build_memory_db(server_module, db_path):
    """A remembered-conversation session for the ``session_export`` MCP tool."""
    import memory_store

    server_module._DB_PATH = str(db_path)
    conn = server_module._open_db()
    try:
        memory_store.touch_session(conn, "S-parity", "proj")
        memory_store.set_session_title(conn, "S-parity", "parity demo")
        memory_store.log_interaction(conn, "I1", "hello, password=%s" % PASSWORD, "",
                                     "hi back", "code", session_id="S-parity",
                                     tokens_in=11, tokens_out=3)
        memory_store.log_interaction(conn, "I2", "second", "", "answer %s" % SECRET,
                                     "code", session_id="S-parity")
    finally:
        conn.close()


def default_exports(tmp_dir):
    """Every default-format export body the ATIF change touches, as text."""
    from sonder_runtime.application.session.http_facade import HttpSessionFacade
    from sonder_runtime.interfaces.http.facades.session import dispatch_session_route

    tmp_dir = Path(tmp_dir)
    repo = build_session_repo(tmp_dir / "sessions.db")
    facade = HttpSessionFacade(repo, max_replay_events=1000)
    out = {}
    for session_id in (PARENT, CHILD):
        body = facade.export(session_id).body
        out["facade.export:" + session_id] = json.dumps(body, sort_keys=True)
        routed = dispatch_session_route(facade, "/v1/sessions/%s/export" % session_id)
        out["route.export:" + session_id] = json.dumps(
            [routed.status_code, routed.body], sort_keys=True)
        bounded = facade.export(session_id, start_sequence=2, end_sequence=9, max_events=5).body
        out["facade.export.bounded:" + session_id] = json.dumps(bounded, sort_keys=True)
        query = facade._query.export_events(session_id)
        out["engine.to_jsonl:" + session_id] = query.to_jsonl()
        out["facade.trajectory:" + session_id] = json.dumps(
            facade.trajectory(session_id).body, sort_keys=True)
    out["facade.export:missing"] = json.dumps(facade.export("nope").body, sort_keys=True)
    out["facade.export:invalid"] = json.dumps(
        [facade.export(" ").status_code, facade.export(" ").body], sort_keys=True)
    import server

    build_memory_db(server, tmp_dir / "mem.db")
    out["mcp.session_export:S-parity"] = server.session_export("S-parity")
    out["mcp.session_export:S-parity:limit1"] = server.session_export("S-parity", limit=1)
    out["mcp.session_export:missing"] = server.session_export("nope")
    out["mcp.session_export:none"] = server.session_export("none")
    return out


def golden(tmp_dir, destination):
    """Write the parity golden from whatever code is importable."""
    Path(destination).write_text(
        json.dumps(default_exports(tmp_dir), indent=1, sort_keys=True) + "\n",
        encoding="utf-8", newline="\n",
    )
