"""Durable single-host storage for the cluster ownership contract.

``SQLiteClusterOwnershipJournal`` persists the owner, epoch, and lease state
used by :mod:`sonder_runtime.domain.cluster_ownership`.  SQLite gives this
adapter restart durability and atomic local transitions; it is deliberately
not a consensus, replication, or fencing provider.  A deployment that needs
automatic takeover must place an equivalent transition journal behind an
external replicated store and fencing authority.

Acquire, renew, and release are serialized with a SQLite write transaction.
An epoch tombstone remains after release so a new owner cannot reuse the old
capability epoch.  The journal stores no task payloads or secrets beyond the
opaque lease token generated by the domain contract.
"""
from __future__ import annotations

from contextlib import contextmanager
import hashlib
import math
from pathlib import Path
import secrets
import sqlite3
import time
from typing import Callable, Iterator

from sonder_runtime.adapters.persistence.owned_sqlite import (
    connect as owned_sqlite_connect,
)
from sonder_runtime.domain.cluster_ownership import (
    ClusterOwnershipAuthority,
    MAX_LEASE_SECONDS,
    OwnerLease,
    OwnershipConflict,
    OwnershipDecision,
    OwnershipError,
    TakeoverDenied,
)


SCHEMA_VERSION = 1
_MAX_EPOCH = (1 << 63) - 1
_BUSY_TIMEOUT_MS = 5000

_EPOCH_COLUMNS = (
    "cluster_id",
    "resource_kind",
    "resource_id",
    "epoch",
    "released_epoch",
    "released_token",
)
_LEASE_COLUMNS = (
    "cluster_id",
    "resource_kind",
    "resource_id",
    "epoch",
    "owner_id",
    "token",
    "expires_at",
    "renew_key",
)

_DDL = (
    """
    CREATE TABLE ownership_epoch (
        cluster_id TEXT NOT NULL,
        resource_kind TEXT NOT NULL,
        resource_id TEXT NOT NULL,
        epoch INTEGER NOT NULL CHECK(epoch >= 0),
        released_epoch INTEGER,
        released_token TEXT,
        PRIMARY KEY(cluster_id, resource_kind, resource_id)
    )
    """,
    """
    CREATE TABLE owner_lease (
        cluster_id TEXT NOT NULL,
        resource_kind TEXT NOT NULL,
        resource_id TEXT NOT NULL,
        epoch INTEGER NOT NULL CHECK(epoch >= 1),
        owner_id TEXT NOT NULL,
        token TEXT NOT NULL,
        expires_at REAL NOT NULL,
        renew_key TEXT,
        PRIMARY KEY(cluster_id, resource_kind, resource_id)
    )
    """,
    """
    CREATE INDEX owner_lease_active_idx
    ON owner_lease(cluster_id, expires_at)
    """,
)


def _lease_seconds(value: object) -> int:
    """Validate the TTL with the same bound as the domain authority."""

    if type(value) is not int or not 1 <= value <= MAX_LEASE_SECONDS:
        raise OwnershipError(
            f"lease_seconds must be an integer within 1..{MAX_LEASE_SECONDS}"
        )
    return value


class SQLiteClusterOwnershipJournal:
    """A durable, single-host adapter for :class:`OwnerLease` transitions.

    The journal opens one short-lived connection per operation.  ``create``
    uses exclusive filesystem creation; reopening always uses SQLite's
    ``mode=rw`` URI, so a typo or deleted journal cannot silently create a new
    authority.  ``connect_factory`` is an explicit test seam and otherwise
    defaults to the runtime's owned SQLite boundary.
    """

    def __init__(
        self,
        path: str | Path,
        *,
        cluster_id: str,
        create: bool = False,
        clock: Callable[[], float] = time.time,
        max_resources: int = 10_000,
        connect_factory: Callable[..., sqlite3.Connection] | None = None,
    ) -> None:
        # Use the domain constructor for the shared identity and capacity
        # contract.  Its in-memory state is intentionally discarded.
        authority = ClusterOwnershipAuthority(
            cluster_id,
            clock=clock,
            max_resources=max_resources,
        )
        self.path = Path(path).absolute()
        self.cluster_id = authority.cluster_id
        self._clock = clock
        self._max_resources = max_resources
        self._connect_factory = connect_factory or owned_sqlite_connect

        if create:
            self._create_schema()
        self._check_open_schema()

    def _create_schema(self) -> None:
        """Enroll a new journal without adopting an existing SQLite file."""

        try:
            self.path.parent.mkdir(parents=True, exist_ok=True)
            with self.path.open("xb"):
                pass
        except FileExistsError as exc:
            raise OwnershipError("owner lease journal already exists") from exc
        except OSError as exc:
            raise OwnershipError("owner lease journal cannot be created") from exc

        connection: sqlite3.Connection | None = None
        try:
            connection = self._open_connection(create=True)
            self._configure_connection(connection)
            connection.execute("BEGIN IMMEDIATE")
            for statement in _DDL:
                connection.execute(statement)
            connection.execute(f"PRAGMA user_version={SCHEMA_VERSION}")
            self._verify_schema(connection)
            connection.commit()
        except OwnershipError:
            if connection is not None:
                connection.rollback()
            raise
        except sqlite3.Error as exc:
            if connection is not None:
                connection.rollback()
            raise OwnershipError("owner lease journal schema could not be created") from exc
        finally:
            if connection is not None:
                connection.close()

    def _open_connection(self, *, create: bool = False) -> sqlite3.Connection:
        if not create and not self.path.is_file():
            raise OwnershipError("owner lease journal is missing")
        database = (
            str(self.path)
            if create
            else self.path.as_uri() + "?mode=rw"
        )
        try:
            return self._connect_factory(
                database,
                uri=not create,
                timeout=5.0,
                isolation_level=None,
            )
        except sqlite3.Error as exc:
            raise OwnershipError("owner lease journal is unavailable") from exc
        except OSError as exc:
            raise OwnershipError("owner lease journal is unavailable") from exc

    @staticmethod
    def _configure_connection(connection: sqlite3.Connection) -> None:
        connection.execute(f"PRAGMA busy_timeout={_BUSY_TIMEOUT_MS}")
        connection.execute("PRAGMA foreign_keys=ON")
        # FULL is required for the journal's local commit to survive a normal
        # process restart.  It does not turn SQLite into a replicated store.
        connection.execute("PRAGMA synchronous=FULL")

    @staticmethod
    def _table_columns(
        connection: sqlite3.Connection,
        table: str,
    ) -> tuple[str, ...]:
        rows = connection.execute(f"PRAGMA table_info({table})").fetchall()
        return tuple(str(row[1]) for row in rows)

    @classmethod
    def _verify_schema(cls, connection: sqlite3.Connection) -> None:
        version = connection.execute("PRAGMA user_version").fetchone()[0]
        if version != SCHEMA_VERSION:
            raise OwnershipError("owner lease journal schema mismatch")
        if cls._table_columns(connection, "ownership_epoch") != _EPOCH_COLUMNS:
            raise OwnershipError("owner lease journal schema mismatch")
        if cls._table_columns(connection, "owner_lease") != _LEASE_COLUMNS:
            raise OwnershipError("owner lease journal schema mismatch")

    def _check_open_schema(self) -> None:
        with self._transaction():
            return None

    @contextmanager
    def _transaction(self) -> Iterator[sqlite3.Connection]:
        connection: sqlite3.Connection | None = None
        try:
            connection = self._open_connection()
            self._configure_connection(connection)
            connection.execute("BEGIN IMMEDIATE")
            self._verify_schema(connection)
            yield connection
            connection.commit()
        except OwnershipError:
            if connection is not None:
                connection.rollback()
            raise
        except sqlite3.Error as exc:
            if connection is not None:
                connection.rollback()
            raise OwnershipError("owner lease journal storage is unavailable") from exc
        except BaseException:
            if connection is not None:
                connection.rollback()
            raise
        finally:
            if connection is not None:
                connection.close()

    def _now(self) -> float:
        value = self._clock()
        if isinstance(value, bool) or not isinstance(value, (int, float)):
            raise OwnershipError("clock returned a non-numeric value")
        try:
            numeric = float(value)
        except (OverflowError, ValueError) as exc:
            raise OwnershipError("clock returned a non-finite value") from exc
        if not math.isfinite(numeric):
            raise OwnershipError("clock returned a non-finite value")
        return numeric

    def _scope(
        self,
        resource_kind: object,
        resource_id: object,
        owner_id: object,
    ) -> tuple[str, str, str]:
        # OwnerLease owns the canonical identity/resource-kind validation.  A
        # short-lived probe avoids duplicating its regex and allowed-kind set.
        probe = OwnerLease(
            self.cluster_id,
            resource_kind,
            resource_id,
            owner_id,
            1,
            "probe",
            0.0,
        )
        return probe.resource_kind, probe.resource_id, probe.owner_id

    @staticmethod
    def _next_epoch(epoch: int) -> int:
        if type(epoch) is not int or not 0 <= epoch < _MAX_EPOCH:
            raise OwnershipError("owner lease epoch is exhausted or invalid")
        return epoch + 1

    def _row_to_lease(self, row: tuple[object, ...]) -> OwnerLease:
        try:
            if (
                type(row[0]) is not str
                or type(row[1]) is not str
                or type(row[2]) is not str
                or type(row[3]) is not int
                or type(row[4]) is not str
                or type(row[5]) is not str
                or isinstance(row[6], bool)
                or not isinstance(row[6], (int, float))
            ):
                raise OwnershipError("owner lease journal contains an invalid lease")
            return OwnerLease(
                row[0],
                row[1],
                row[2],
                row[4],
                row[3],
                row[5],
                row[6],
            )
        except (TypeError, ValueError, OwnershipError) as exc:
            raise OwnershipError("owner lease journal contains an invalid lease") from exc

    def _load_lease(
        self,
        connection: sqlite3.Connection,
        resource_kind: str,
        resource_id: str,
    ) -> tuple[OwnerLease, str | None] | None:
        row = connection.execute(
            "SELECT cluster_id,resource_kind,resource_id,epoch,owner_id,token,"
            "expires_at,renew_key FROM owner_lease "
            "WHERE cluster_id=? AND resource_kind=? AND resource_id=?",
            (self.cluster_id, resource_kind, resource_id),
        ).fetchone()
        if row is None:
            return None
        if row[7] is not None and type(row[7]) is not str:
            raise OwnershipError("owner lease journal contains an invalid renewal key")
        return self._row_to_lease(row), None if row[7] is None else str(row[7])

    def _epoch_row(
        self,
        connection: sqlite3.Connection,
        resource_kind: str,
        resource_id: str,
    ) -> tuple[int, int | None, str | None] | None:
        row = connection.execute(
            "SELECT epoch,released_epoch,released_token FROM ownership_epoch "
            "WHERE cluster_id=? AND resource_kind=? AND resource_id=?",
            (self.cluster_id, resource_kind, resource_id),
        ).fetchone()
        if row is None:
            return None
        if type(row[0]) is not int:
            raise OwnershipError("owner lease journal contains an invalid epoch")
        if row[1] is not None and type(row[1]) is not int:
            raise OwnershipError("owner lease journal contains an invalid release epoch")
        if row[2] is not None and type(row[2]) is not str:
            raise OwnershipError("owner lease journal contains an invalid release token")
        epoch = row[0]
        released_epoch = row[1]
        if not 0 <= epoch <= _MAX_EPOCH:
            raise OwnershipError("owner lease journal contains an invalid epoch")
        if released_epoch is not None and not 1 <= released_epoch <= _MAX_EPOCH:
            raise OwnershipError("owner lease journal contains an invalid release epoch")
        return epoch, released_epoch, None if row[2] is None else str(row[2])

    def _active_count(self, connection: sqlite3.Connection, now: float) -> int:
        row = connection.execute(
            "SELECT count(*) FROM owner_lease WHERE cluster_id=? AND expires_at>?",
            (self.cluster_id, now),
        ).fetchone()
        return int(row[0])

    def _new_epoch(
        self,
        connection: sqlite3.Connection,
        resource_kind: str,
        resource_id: str,
        *,
        current_epoch: int | None = None,
    ) -> int:
        prior = self._epoch_row(connection, resource_kind, resource_id)
        if prior is None:
            epoch = 1
            connection.execute(
                "INSERT INTO ownership_epoch "
                "(cluster_id,resource_kind,resource_id,epoch,released_epoch,released_token) "
                "VALUES (?,?,?,?,NULL,NULL)",
                (self.cluster_id, resource_kind, resource_id, epoch),
            )
            return epoch
        if current_epoch is not None and prior[0] != current_epoch:
            raise OwnershipConflict("ownership epoch changed during acquire")
        epoch = self._next_epoch(prior[0])
        connection.execute(
            "UPDATE ownership_epoch SET epoch=?,released_epoch=NULL,released_token=NULL "
            "WHERE cluster_id=? AND resource_kind=? AND resource_id=? AND epoch=?",
            (
                epoch,
                self.cluster_id,
                resource_kind,
                resource_id,
                prior[0],
            ),
        )
        return epoch

    def acquire(
        self,
        resource_kind: str,
        resource_id: str,
        owner_id: str,
        *,
        lease_seconds: int = 30,
    ) -> OwnerLease:
        """Acquire a lease, or return the current lease for the same owner.

        Same-owner acquisition is idempotent and does not silently alter the
        existing expiry.  A different owner must wait for expiry and acquire
        a strictly newer epoch.
        """

        kind, resource, owner = self._scope(resource_kind, resource_id, owner_id)
        ttl = _lease_seconds(lease_seconds)
        with self._transaction() as connection:
            now = self._now()
            loaded = self._load_lease(connection, kind, resource)
            if loaded is not None:
                current, _ = loaded
                if now < current.expires_at:
                    if current.owner_id == owner:
                        return current
                    raise OwnershipConflict("resource is already owned")
                epoch = self._new_epoch(
                    connection,
                    kind,
                    resource,
                    current_epoch=current.epoch,
                )
                lease = OwnerLease(
                    self.cluster_id,
                    kind,
                    resource,
                    owner,
                    epoch,
                    # ``OwnerLease`` identities begin with an alphanumeric;
                    # hex avoids the leading '-'/'_' values possible from
                    # token_urlsafe while retaining cryptographic entropy.
                    secrets.token_hex(24),
                    now + ttl,
                )
                changed = connection.execute(
                    "UPDATE owner_lease SET epoch=?,owner_id=?,token=?,expires_at=?,renew_key=NULL "
                    "WHERE cluster_id=? AND resource_kind=? AND resource_id=? "
                    "AND epoch=? AND token=?",
                    (
                        lease.epoch,
                        lease.owner_id,
                        lease.token,
                        lease.expires_at,
                        self.cluster_id,
                        kind,
                        resource,
                        current.epoch,
                        current.token,
                    ),
                ).rowcount
                if changed != 1:
                    raise OwnershipConflict("ownership changed during acquire")
                return lease

            if self._active_count(connection, now) >= self._max_resources:
                raise OwnershipConflict("ownership resource capacity exhausted")
            epoch = self._new_epoch(connection, kind, resource)
            lease = OwnerLease(
                self.cluster_id,
                kind,
                resource,
                owner,
                epoch,
                secrets.token_hex(24),
                now + ttl,
            )
            try:
                connection.execute(
                    "INSERT INTO owner_lease "
                    "(cluster_id,resource_kind,resource_id,epoch,owner_id,token,expires_at,renew_key) "
                    "VALUES (?,?,?,?,?,?,?,NULL)",
                    (
                        lease.cluster_id,
                        lease.resource_kind,
                        lease.resource_id,
                        lease.epoch,
                        lease.owner_id,
                        lease.token,
                        lease.expires_at,
                    ),
                )
            except sqlite3.IntegrityError as exc:
                raise OwnershipConflict("ownership changed during acquire") from exc
            return lease

    @staticmethod
    def _decision(
        requested: OwnerLease,
        current: OwnerLease | None,
        *,
        now: float | None = None,
    ) -> OwnershipDecision:
        if current is None:
            return OwnershipDecision(False, "no_owner")
        if current.epoch != requested.epoch:
            return OwnershipDecision(False, "stale_epoch", current.epoch)
        if current.owner_id != requested.owner_id:
            return OwnershipDecision(False, "owner_mismatch", current.epoch)
        if current.token != requested.token:
            return OwnershipDecision(False, "stale_lease", current.epoch)
        if now is not None and now >= current.expires_at:
            return OwnershipDecision(False, "lease_expired", current.epoch)
        return OwnershipDecision(True, "current", current.epoch)

    def validate(self, lease: OwnerLease) -> OwnershipDecision:
        """Check a lease against the durable current owner."""

        if not isinstance(lease, OwnerLease):
            return OwnershipDecision(False, "invalid_lease")
        if lease.cluster_id != self.cluster_id:
            return OwnershipDecision(False, "cluster_mismatch")
        with self._transaction() as connection:
            loaded = self._load_lease(connection, lease.resource_kind, lease.resource_id)
            if loaded is None:
                return OwnershipDecision(False, "no_owner")
            current, _ = loaded
            return self._decision(lease, current, now=self._now())

    @staticmethod
    def _renew_key(lease: OwnerLease, lease_seconds: int) -> str:
        # Include the supplied expiry so an intentional renewal from the
        # newly returned lease is distinct from a retry of the old request.
        payload = "\x1f".join(
            (
                lease.cluster_id,
                lease.resource_kind,
                lease.resource_id,
                lease.owner_id,
                str(lease.epoch),
                lease.token,
                float(lease.expires_at).hex(),
                str(lease_seconds),
            )
        ).encode("utf-8")
        return hashlib.sha256(payload).hexdigest()

    def renew(self, lease: OwnerLease, *, lease_seconds: int = 30) -> OwnerLease:
        """Renew a current lease; replaying the same request returns its result."""

        ttl = _lease_seconds(lease_seconds)
        if not isinstance(lease, OwnerLease):
            raise OwnershipConflict("invalid_lease")
        if lease.cluster_id != self.cluster_id:
            raise OwnershipConflict("cluster_mismatch")
        request_key = self._renew_key(lease, ttl)
        with self._transaction() as connection:
            loaded = self._load_lease(connection, lease.resource_kind, lease.resource_id)
            current = None if loaded is None else loaded[0]
            now = self._now() if current is not None else None
            decision = self._decision(lease, current, now=now)
            if not decision.allowed:
                raise OwnershipConflict(decision.reason)
            stored_key = None if loaded is None else loaded[1]
            if stored_key == request_key:
                return current
            if current is None:
                # Kept explicit even though an allowed decision currently
                # implies a current row; fail closed if that invariant ever
                # changes.
                raise OwnershipConflict("no_owner")
            if now is None:
                raise OwnershipError("clock did not produce a renewal time")
            expires_at = now + ttl
            if expires_at <= current.expires_at:
                # Wall clocks can move backward and a same-second renewal can
                # otherwise produce an indistinguishable or shorter lease.
                expires_at = math.nextafter(current.expires_at, math.inf)
                if not math.isfinite(expires_at):
                    raise OwnershipError("owner lease expiry is exhausted")
            renewed = OwnerLease(
                current.cluster_id,
                current.resource_kind,
                current.resource_id,
                current.owner_id,
                current.epoch,
                current.token,
                expires_at,
            )
            changed = connection.execute(
                "UPDATE owner_lease SET expires_at=?,renew_key=? "
                "WHERE cluster_id=? AND resource_kind=? AND resource_id=? "
                "AND epoch=? AND owner_id=? AND token=? AND expires_at=?",
                (
                    renewed.expires_at,
                    request_key,
                    self.cluster_id,
                    lease.resource_kind,
                    lease.resource_id,
                    current.epoch,
                    current.owner_id,
                    current.token,
                    current.expires_at,
                ),
            ).rowcount
            if changed != 1:
                raise OwnershipConflict("ownership changed during renewal")
            return renewed

    def release(self, lease: OwnerLease) -> bool:
        """Release an exact lease and retain a replayable release tombstone."""

        if not isinstance(lease, OwnerLease) or lease.cluster_id != self.cluster_id:
            return False
        with self._transaction() as connection:
            loaded = self._load_lease(connection, lease.resource_kind, lease.resource_id)
            if loaded is not None:
                current, _ = loaded
                if current != lease:
                    return False
                changed = connection.execute(
                    "DELETE FROM owner_lease WHERE cluster_id=? AND resource_kind=? "
                    "AND resource_id=? AND epoch=? AND token=? AND expires_at=?",
                    (
                        self.cluster_id,
                        lease.resource_kind,
                        lease.resource_id,
                        lease.epoch,
                        lease.token,
                        lease.expires_at,
                    ),
                ).rowcount
                if changed != 1:
                    return False
                tombstone = self._epoch_row(
                    connection,
                    lease.resource_kind,
                    lease.resource_id,
                )
                if tombstone is None or tombstone[0] != lease.epoch:
                    raise OwnershipError("owner lease epoch tombstone is missing")
                connection.execute(
                    "UPDATE ownership_epoch SET released_epoch=?,released_token=? "
                    "WHERE cluster_id=? AND resource_kind=? AND resource_id=? AND epoch=?",
                    (
                        lease.epoch,
                        lease.token,
                        self.cluster_id,
                        lease.resource_kind,
                        lease.resource_id,
                        lease.epoch,
                    ),
                )
                return True

            tombstone = self._epoch_row(
                connection,
                lease.resource_kind,
                lease.resource_id,
            )
            return bool(
                tombstone is not None
                and tombstone[0] == lease.epoch
                and tombstone[1] == lease.epoch
                and tombstone[2] == lease.token
            )

    def takeover(
        self,
        proof: object,
        *,
        new_owner_id: str,
        lease_seconds: int = 30,
        resource_id: str | None = None,
    ) -> OwnerLease:
        """Reject takeover until an external replicated/fencing adapter exists.

        Keeping this boundary explicit prevents callers from mistaking a
        durable local SQLite file for automatic failover authority.
        """

        raise TakeoverDenied(
            "automatic takeover requires external fencing and replicated proof; "
            "the SQLite journal is single-host"
        )


__all__ = ["SCHEMA_VERSION", "SQLiteClusterOwnershipJournal"]
