"""Explicit ports (SPEC-3 R-M4).

Model calls, repositories, clocks, process probes, filesystems,
executors, event sinks, and transactions are reached only through these
interfaces. Ports raise the domain error taxonomy, never transport or
driver exceptions.
"""
from .backup import BackupGateway, BackupPath, BackupResultView
from .archive_create import ArchiveCreateGateway, ArchiveCreateRequest
from .clock import Clock
from .event_sink import EventSink
from .model_gateway import (
    Embedding,
    InferenceTelemetry,
    ModelGateway,
    ModelRequest,
    ModelResponse,
)
from .vision_gateway import (
    VisionGateway,
    VisionInput,
    VisionInputProvider,
    VisionRequest,
    VisionResponse,
)
from .process_probe import ProbeResult, ProcessIdentity, ProcessProbe
from .recall import RecallGateway
from .preferences import PreferenceCodec, PreferenceEventSink, PreferenceRepository
from .repositories import (
    AutomationRepository,
    MemoryRepository,
    PolicyRepository,
    UnitOfWork,
)
from .tool_executor import ToolCall, ToolExecutor, ToolResult
from .task_state import ChecklistEventPort, TaskRepository
from .workflows import LoopRunner, WorkflowRepository
from .artifact_store import (
    ArtifactHandle, AttachmentStore, SpillHandle, SpillSnapshot, SpillSpec,
    SpillState, SpillStore,
)
from .telemetry_sink import TelemetryEvent, TelemetryRedactor, TelemetrySink
from .web import (
    CredentialLease,
    CredentialProvider,
    CredentialRequest,
    CredentialScope,
    EgressPolicy,
    ProviderHealth,
    ProviderHealthSnapshot,
    WebPolicyError,
    WebProvider,
    WebRequest,
    WebResponse,
    redact,
)
from .jobs import (
    JobClaim,
    JobIdentity,
    JobRecord,
    JobRegistry,
    JobStatus,
    WorkflowCheckpoint,
    WorkflowDefinition,
    WorkflowEngine,
    WorkflowRepository as JobWorkflowRepository,
    WorkflowResume,
    WorkflowStep,
)
from .execution_world import (
    CleanupResult,
    ExecutionHandle,
    ExecutionResult,
    ExecutionWorld,
    ExecutionWorldSnapshot,
    ExecutionWorldSpec,
    ExecutionWorldState,
    ShellExecutor,
    ShellRequest,
    SubprocessHandle,
    SubprocessRequest,
    SubprocessRuntime,
    TerminalChunk,
    TerminalHandle,
    TerminalRequest,
    TerminalService,
)
from .sandbox import (
    SandboxCleanupResult,
    SandboxPolicy,
    SandboxProvider,
    SandboxResourceLimits,
    SandboxWorld,
    SandboxWorldKind,
    SandboxWorldSnapshot,
    SandboxWorldSpec,
    SandboxWorldState,
)
from .subagents import (
    InvalidSubagentRequest,
    SubagentBudget,
    SubagentError,
    SubagentHandle,
    SubagentProtocolError,
    SubagentProvider,
    SubagentRequest,
    SubagentResult,
    SubagentSnapshot,
    SubagentStatus,
    SubagentUsage,
    TERMINAL_SUBAGENT_STATUSES,
    validate_child_budget,
)
from .specialized_lifecycle import (
    ActivationRequest,
    ActivationResult,
    CleanupResult,
    DeploymentResult,
    EmbeddingProvider,
    EmbeddingRequest,
    EmbeddingResult,
    HealthReport,
    HealthStatus,
    TrainingBackend,
    TrainingRequest,
    UpdateActivator,
)

__all__ = [
    "AutomationRepository",
    "ArchiveCreateGateway",
    "ArchiveCreateRequest",
    "BackupGateway",
    "BackupPath",
    "BackupResultView",
    "ChecklistEventPort",
    "Clock",
    "Embedding",
    "EventSink",
    "InferenceTelemetry",
    "MemoryRepository",
    "ModelGateway",
    "ModelRequest",
    "ModelResponse",
    "VisionGateway",
    "VisionInput",
    "VisionInputProvider",
    "VisionRequest",
    "VisionResponse",
    "PolicyRepository",
    "PreferenceCodec",
    "PreferenceEventSink",
    "PreferenceRepository",
    "ProbeResult",
    "ProcessIdentity",
    "ProcessProbe",
    "RecallGateway",
    "ToolCall",
    "ToolExecutor",
    "ToolResult",
    "TaskRepository",
    "UnitOfWork",
    "LoopRunner",
    "WorkflowRepository",
    "JobClaim",
    "JobIdentity",
    "JobRecord",
    "JobRegistry",
    "JobStatus",
    "WorkflowCheckpoint",
    "WorkflowDefinition",
    "WorkflowEngine",
    "JobWorkflowRepository",
    "WorkflowResume",
    "WorkflowStep",
    "CleanupResult",
    "ExecutionHandle",
    "ExecutionResult",
    "ExecutionWorld",
    "ExecutionWorldSnapshot",
    "ExecutionWorldSpec",
    "ExecutionWorldState",
    "ShellExecutor",
    "ShellRequest",
    "SubprocessHandle",
    "SubprocessRequest",
    "SubprocessRuntime",
    "TerminalChunk",
    "TerminalHandle",
    "TerminalRequest",
    "TerminalService",
    "SandboxCleanupResult",
    "SandboxPolicy",
    "SandboxProvider",
    "SandboxResourceLimits",
    "SandboxWorld",
    "SandboxWorldKind",
    "SandboxWorldSnapshot",
    "SandboxWorldSpec",
    "SandboxWorldState",
    "InvalidSubagentRequest",
    "SubagentBudget",
    "SubagentError",
    "SubagentHandle",
    "SubagentProtocolError",
    "SubagentProvider",
    "SubagentRequest",
    "SubagentResult",
    "SubagentSnapshot",
    "SubagentStatus",
    "SubagentUsage",
    "TERMINAL_SUBAGENT_STATUSES",
    "validate_child_budget",
    "ActivationRequest",
    "ActivationResult",
    "CleanupResult",
    "DeploymentResult",
    "EmbeddingProvider",
    "EmbeddingRequest",
    "EmbeddingResult",
    "HealthReport",
    "HealthStatus",
    "TrainingBackend",
    "TrainingRequest",
    "UpdateActivator",
    "ArtifactHandle",
    "AttachmentStore",
    "SpillHandle",
    "SpillSnapshot",
    "SpillSpec",
    "SpillState",
    "SpillStore",
    "TelemetryEvent",
    "TelemetryRedactor",
    "TelemetrySink",
    "CredentialLease",
    "CredentialProvider",
    "CredentialRequest",
    "CredentialScope",
    "EgressPolicy",
    "ProviderHealth",
    "ProviderHealthSnapshot",
    "WebPolicyError",
    "WebProvider",
    "WebRequest",
    "WebResponse",
    "redact",
]
