"""Port for command discovery at a served interface."""
from __future__ import annotations

from typing import Any, Protocol


class CommandCatalog(Protocol):
    def catalog(self) -> Any: ...
    def http_catalog(self) -> Any: ...
    def http_slash_tools(self) -> Any: ...
    def by_name(self, name: str) -> Any: ...
    def complete(self, prefix: str, **kwargs: Any) -> Any: ...
    def help_text(self, topic: str = "") -> str: ...
    def parse_invocation(self, line: str) -> Any: ...


__all__ = ["CommandCatalog"]
