"""Port for callers that need the runtime permission policy."""
from __future__ import annotations

from typing import Any, Protocol


class PermissionPolicy(Protocol):
    def decide_for_caller(self, tool_name: str, *, interactive: bool,
                          gate_control_exempt: bool, surface: str = "",
                          record: bool = True, mode: str | None = None,
                          rule_lookup: Any = None) -> Any: ...
    def set_mode(self, name: str) -> str: ...
    def modes(self) -> tuple[str, ...]: ...
    def is_durable_authority_tool(self, name: str) -> bool: ...
    def mode_label(self, mode: str) -> str: ...
    def gate_control_tools(self) -> frozenset[str]: ...
    def allow_action(self) -> str: ...
    def ask_action(self) -> str: ...
    def deny_action(self) -> str: ...


__all__ = ["PermissionPolicy"]
